name: End-to-end tests
on: push
jobs:
  cypress-run:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # Install npm dependencies, cache them correctly
      # and run all Cypress tests

      - name: Install dependencies
        run: npm install

      - name: Clear reports directory
        if: success() || failure()
        run: npm run clean-reports

      - name: Cypress run
        uses: cypress-io/github-action@v6

      # after the test run completes store videos and any screenshots
      - name: upload artifacts-screenshot
        uses: actions/upload-artifact@v4
        # add the line below to store screenshots only on failures
        if: failure()
        with:
          name: cypress-screenshots
          path: cypress/screenshots
          if-no-files-found: ignore # 'warn' or 'error' are also available, defaults to `warn`

      - name: upload artifacts-video
        uses: actions/upload-artifact@v4
        if: failure()
        with:
          name: cypress-videos
          path: cypress/videos
          if-no-files-found: ignore # 'warn' or 'error' are also available, defaults to `warn`

      - name: merge reports
        if: success() || failure()
        run: npm run report:merge

      - name: Generate HTML report
        if: success() || failure()
        run: npm run report:generate

      # Integrate html reports
      - name: upload artifacts-reports
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: cypress-execution-report
          path: mochawesome-report
          retention-days: 30

      # Integrate slack notifications
      - name: Slack Notification
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
          SLACK_USERNAME: ci-demo
          SLACK_TITLE: Slack notification
          SLACK_MESSAGE: 'Message'
          SLACK_COLOR: ${{ job.status }}
